### PR TITLE
Forking repos disables the Issues tab

### PR DESCRIPTION
**Pull request by dandv**
Hey @cscott,

I found this package at https://atmospherejs.com/cscottnet/geolocation and was wondering what the differences are from the original, since the README is identical.

If it was just an experiment, you can hide the old package from Atmosphere searches, but still keep it installable by dependent packages and apps:

```
meteor admin set-unmigrated cscottnet:geolocation
```

After looking at the [improve-geolocation branch](https://github.com/cscott/mobile-packages/commit/2ca44285fa4431f87943378ad77d9245cb0ff0b3), it seems that you've made some changes that should be merged into master before publishing on Atmosphere. That will also take care of updating the README. The master branch in this GitHub repo is behind what's released on Atmosphere - I see v1.0.4 published there in Jan 2015, but the last commit here was from December.

As always, a PR against the original repo would be best, and if not accepted, that should be mentioned in the README.

Thanks,
Dan
Atmosphere curator

### CODE REVIEW

**Comment by cscott** [comment]
https://github.com/meteor/mobile-packages/pull/36

**Comment by cscott** [comment]
I submitted the PR three months ago.

**Comment by dandv** [comment]
I see. Hope @stubailo gets to it soon.

In the meantime, would you like to enable the Issues tab for this repo, @cscott ?

**Comment by cscott** [comment]
Not really: I don't plan to maintain this package. Any issues you wish to
file should really be filed upstream.  Why can't you open an issue there?

**Comment by dandv** [comment]
Sorry to have irked you.

I'm a curator of Atmosphere packages and am just trying to clean up the multitude of packages providing a given functionality, in order to reduce the [paradox of choice](http://www.ted.com/talks/barry_schwartz_on_the_paradox_of_choice).

If you don't plan to maintain that package, that's perfectly fine. Out of courtesy for the user, I would like to ask for a note in the README explaining the differences from the original, or to hide the package from Atmosphere searches while keeping it installable by your apps and dependents:

```
meteor admin set-unmigrated cscottnet:geolocation
```

Of course, by no means do you _have_ to do this.

**Comment by cscott** [comment]
Well, the best way to reduce the paradox of choice here is to get the
upstream maintainer to be more responsive.​

**Pull request closed without merging**
